name: eliteclean
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  flutter_riverpod: ^2.5.1
  firebase_core: ^3.6.0
  shared_preferences: ^2.3.2
  http: ^1.2.2
  firebase_auth: ^5.3.1

  cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - public/images/icon-32-x-clean.svg
    - public/images/logo-icon.svg
    - public/images/icon-16-x-phone.svg
    - public/images/emptyservice.png
    - public/images/bathroom.png