name: eliteclean
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.3.2
  firebase_core: ^3.6.0
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.3.1
  flutter_map: ^7.0.1
  latlong2: ^0.9.0
  geolocator: ^13.0.1
  cloud_firestore: ^5.4.4
  firebase_database: ^11.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
